### PR TITLE
Add svg screencast

### PR DESCRIPTION
**Pull request by marionebl**
* Add `screenshot.js`
* Better quality
* Smaller file

```sh
svg-term-cli --command="node screenshot" \
 --at=1000 \ 
 --padding-x=10 \
 --padding-y=0 \
 --height=9 \
 --no-cursor \
 --width=64 \
 --out=screenshot.svg
```

### CODE REVIEW

**Comment by siddharthkp** [comment]
😯 whoa, this is pretty cool!

How do you generate that?

Also, how do we pick the same colors consistently, this seems to be terminal dependant (I like the current colors coz they are bright and fun)

**Comment by marionebl** [comment]
I created the file via `svg-term-cli`, e.g.:

```sh
npm install -g svg-term-cli@next
svg-term --command="node screenshot" --at=1000 --padding-x=10 --padding-y=0 --height=9 --no-cursor --width=64 --out=screenshot.svg
```

`svg-term-cli` supports all a broad range of color profiles, by using the same the file can be generated independent from local setups. What terminal program/color profile combination did you use for the original screenshot?

**Comment by siddharthkp** [comment]
> What terminal program/color profile combination did you use for the original screenshot?

I use hyper with the [hyper-snazzy](https://github.com/sindresorhus/hyper-snazzy) theme

**Comment by marionebl** [comment]
Updated to use the snazzy color profile as requested

**Comment by siddharthkp** [comment]
Thanks!

**Pull request merged**
