### PR TITLE
Upgrade to latest chalk version #4

### LINKED ISSUE #4: Upgrade to latest chalk version
Chalk has released a new version last month and I guess it is better to upgrade chalk to the latest version.

### PR DESCRIPTION
**Pull request by cg-cnu**
Upgraded chlak from `1.1.3` to `2.1.0`. Closes #4

### CODE REVIEW

**Comment by cg-cnu** [comment]
Did couple of manual tests and everything seems to be working fine.

**Comment by siddharthkp** [comment]
This repo uses npm5's package-lock 🙂

you'll have to install using npm5 to update it, sorry about that

**Comment by cg-cnu** [comment]
committed the package-lock  🙂

**Comment by siddharthkp** [comment]
Thanks! Published in prettycli@1.4.3 🎉

**Pull request merged**
